import type { OnokunSatooyaClusterKey, OnokunSatooyaTypeKey } from "./onokunSatooyaTypes";

export type OnokunSatooyaChapterKey = "prologue" | "know" | "enjoy" | "quest";
export type OnokunAnswerValue = 1 | 2 | 3 | 4 | 5;

export interface OnokunEvidence {
  type: OnokunSatooyaTypeKey;
  weight: number;
}

export interface OnokunChoice {
  value: OnokunAnswerValue;
  label: string;
}

export interface OnokunSatooyaQuestion {
  id: string;
  chapter: OnokunSatooyaChapterKey;
  chapterTitle: string;
  scene: string;
  text: string;
  primaryType: OnokunSatooyaTypeKey;
  primaryCluster: OnokunSatooyaClusterKey;
  choices: OnokunChoice[];
  evidenceByAnswer: Record<OnokunAnswerValue, OnokunEvidence[]>;
}

export const defaultOnokunChoices: OnokunChoice[] = [
  { value: 1, label: "左の感じが近い" },
  { value: 2, label: "どちらかといえば左" },
  { value: 3, label: "まんなかくらい" },
  { value: 4, label: "どちらかといえば右" },
  { value: 5, label: "右の感じが近い" },
];

function evidence(
  primaryType: OnokunSatooyaTypeKey,
  nearType: OnokunSatooyaTypeKey,
  middleType: OnokunSatooyaTypeKey,
  counterType: OnokunSatooyaTypeKey,
  farType: OnokunSatooyaTypeKey,
): Record<OnokunAnswerValue, OnokunEvidence[]> {
  return {
    5: [
      { type: primaryType, weight: 3 },
      { type: nearType, weight: 1 },
    ],
    4: [
      { type: primaryType, weight: 2 },
      { type: nearType, weight: 1 },
    ],
    3: [
      { type: middleType, weight: 1 },
      { type: nearType, weight: 1 },
    ],
    2: [
      { type: counterType, weight: 1 },
      { type: middleType, weight: 1 },
    ],
    1: [
      { type: farType, weight: 2 },
      { type: counterType, weight: 1 },
    ],
  };
}

export const onokunSatooyaQuestions: OnokunSatooyaQuestion[] = [
  {
    id: "q01",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "はじまりの気持ち",
    text: "うちの子と出会ったとき、近かった気持ちはどちら？",
    primaryType: "warm-watch",
    primaryCluster: "grow",
    choices: [
      { value: 1, label: "見た目のかわいさを誰かに見せたい" },
      { value: 2, label: "飾ったり写真に残したくなった" },
      { value: 3, label: "どんな背景があるのか気になった" },
      { value: 4, label: "そばにいると少しほっとした" },
      { value: 5, label: "家族が増えたような気持ちになった" },
    ],
    evidenceByAnswer: evidence(
      "warm-watch",
      "chikuchiku-care",
      "town-finder",
      "uchinoko-world",
      "goen-talk",
    ),
  },
  {
    id: "q02",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "背景への触れ方",
    text: "おのくんが生まれた背景に触れるとき、自然に近いのは？",
    primaryType: "word-tuner",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "まずは静かに受け止めたい" },
      { value: 2, label: "そばにいる人とゆっくり話したい" },
      { value: 3, label: "自分なりに調べて知りたい" },
      { value: 4, label: "大切なことを伝わる言葉にしたい" },
      { value: 5, label: "敬意を持って誰かに紹介したい" },
    ],
    evidenceByAnswer: evidence("word-tuner", "town-finder", "goen-talk", "warm-watch", "chikuchiku-care"),
  },
  {
    id: "q03",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "手づくりの見え方",
    text: "手づくりのおのくんを見て、最初に目が向きやすいのは？",
    primaryType: "chikuchiku-care",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "写真にしたときの雰囲気" },
      { value: 2, label: "一体一体違う表情" },
      { value: 3, label: "どんな人が作っているのか" },
      { value: 4, label: "縫い目や手ざわりのあたたかさ" },
      { value: 5, label: "大切に育てられてきた感じ" },
    ],
    evidenceByAnswer: evidence("chikuchiku-care", "warm-watch", "town-finder", "uchinoko-world", "mendokushe-breakthrough"),
  },
  {
    id: "q04",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "東松島との距離",
    text: "東松島や里帰りの話を聞いたとき、近い反応は？",
    primaryType: "tadaima-starter",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "まずは家でうちの子を眺めたい" },
      { value: 2, label: "写真や情報を少し見てみたい" },
      { value: 3, label: "誰かの体験談を聞いてみたい" },
      { value: 4, label: "いつか行けたらいいなと思う" },
      { value: 5, label: "行くきっかけを作りたくなる" },
    ],
    evidenceByAnswer: evidence("tadaima-starter", "town-finder", "goen-talk", "warm-watch", "chikuchiku-care"),
  },
  {
    id: "q05",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "はじめての人への紹介",
    text: "おのくんを知らない人に話すなら、どこから話したい？",
    primaryType: "goen-talk",
    primaryCluster: "grow",
    choices: [
      { value: 1, label: "うちの子の写真や表情" },
      { value: 2, label: "迎えたときの自分の気持ち" },
      { value: 3, label: "おのくんの背景や場所" },
      { value: 4, label: "里親さん同士の楽しさ" },
      { value: 5, label: "会話が広がる感じ" },
    ],
    evidenceByAnswer: evidence("goen-talk", "word-tuner", "town-finder", "uchinoko-world", "warm-watch"),
  },
  {
    id: "q06",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "情報との関わり",
    text: "おのくんの活動や場所の情報を見つけたら、どうしたくなる？",
    primaryType: "town-finder",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "必要なときまで静かに覚えておく" },
      { value: 2, label: "近い人とだけ話してみる" },
      { value: 3, label: "言葉を整えて紹介したくなる" },
      { value: 4, label: "あとで見返せるように残したい" },
      { value: 5, label: "行きたい人に届けたくなる" },
    ],
    evidenceByAnswer: evidence("town-finder", "word-tuner", "goen-talk", "warm-watch", "outing-arranger"),
  },
  {
    id: "q07",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "防災への入口",
    text: "防災につながる集まりを知ったとき、近い入口は？",
    primaryType: "outing-arranger",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "怖さより、まず安心して話せる場が大事" },
      { value: 2, label: "知っている人がいるならのぞいてみたい" },
      { value: 3, label: "何をする場なのか知りたい" },
      { value: 4, label: "参加しやすい流れがあると行けそう" },
      { value: 5, label: "楽しく集まる形なら整えてみたい" },
    ],
    evidenceByAnswer: evidence("outing-arranger", "back-pat", "town-finder", "warm-watch", "goen-talk"),
  },
  {
    id: "q08",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "楽しい備え",
    text: "「楽しいから集まる、集まるから備えになる」と聞いて、近いのは？",
    primaryType: "back-pat",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "まずは安心できる空気を大切にしたい" },
      { value: 2, label: "誰かと話せるなら参加しやすい" },
      { value: 3, label: "意味がわかると動きやすい" },
      { value: 4, label: "誰かの一歩を応援したい" },
      { value: 5, label: "気軽に来られるきっかけを作りたい" },
    ],
    evidenceByAnswer: evidence("back-pat", "tadaima-starter", "word-tuner", "warm-watch", "goen-talk"),
  },
  {
    id: "q09",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "ちょっと変わった入口",
    text: "おのくんの楽しみ方で、まだ見たことのない案を聞いたら？",
    primaryType: "mendokushe-breakthrough",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "まずは意味や背景を知りたい" },
      { value: 2, label: "できる段取りがあれば考えたい" },
      { value: 3, label: "誰が楽しめるか想像したい" },
      { value: 4, label: "ちょっと試すなら面白そう" },
      { value: 5, label: "変わっていて、すぐやってみたい" },
    ],
    evidenceByAnswer: evidence("mendokushe-breakthrough", "wakuwaku-future", "goen-talk", "outing-arranger", "word-tuner"),
  },
  {
    id: "q10",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "未来への広がり",
    text: "うちの子とのこれからを考えると、近いのは？",
    primaryType: "wakuwaku-future",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "今のぬくもりを大切にしたい" },
      { value: 2, label: "少しずつ手をかけて育てたい" },
      { value: 3, label: "誰かと話しながら考えたい" },
      { value: 4, label: "やってみたいことが浮かぶ" },
      { value: 5, label: "楽しみ方をもっと広げたくなる" },
    ],
    evidenceByAnswer: evidence("wakuwaku-future", "mendokushe-breakthrough", "goen-talk", "chikuchiku-care", "warm-watch"),
  },
  {
    id: "q11",
    chapter: "know",
    chapterTitle: "第1章 おのくんを知る",
    scene: "世界観の入口",
    text: "たくさんのおのくんが並んでいる写真を見たら、まず感じるのは？",
    primaryType: "uchinoko-world",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "一体一体を大切に見守りたい" },
      { value: 2, label: "どんな人の手でできたか気になる" },
      { value: 3, label: "誰かと感想を話したい" },
      { value: 4, label: "違いが見える写真として面白い" },
      { value: 5, label: "うちの子らしい見せ方を考えたい" },
    ],
    evidenceByAnswer: evidence("uchinoko-world", "mendokushe-breakthrough", "goen-talk", "chikuchiku-care", "warm-watch"),
  },
  {
    id: "q12",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "写真を撮る日",
    text: "うちの子を撮るなら、どんな撮り方が近い？",
    primaryType: "uchinoko-world",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "撮るより、そばに置いて眺めたい" },
      { value: 2, label: "日常の記録として残したい" },
      { value: 3, label: "誰かに見せる話題にしたい" },
      { value: 4, label: "背景や小物も少し合わせたい" },
      { value: 5, label: "うちの子の世界観まで作りたい" },
    ],
    evidenceByAnswer: evidence("uchinoko-world", "wakuwaku-future", "goen-talk", "town-finder", "warm-watch"),
  },
  {
    id: "q13",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "いつもの置き場所",
    text: "うちの子の居場所を整えるとき、近いのは？",
    primaryType: "chikuchiku-care",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "まずは見た目のかわいさを大事にする" },
      { value: 2, label: "写真に映る雰囲気を考える" },
      { value: 3, label: "家族や誰かと話しながら決める" },
      { value: 4, label: "手ざわりや置き心地を整えたい" },
      { value: 5, label: "長く大切にできる場所にしたい" },
    ],
    evidenceByAnswer: evidence("chikuchiku-care", "warm-watch", "goen-talk", "uchinoko-world", "mendokushe-breakthrough"),
  },
  {
    id: "q14",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "誰かに見せる",
    text: "うちの子を誰かに見せるなら、どんな感じが近い？",
    primaryType: "goen-talk",
    primaryCluster: "grow",
    choices: [
      { value: 1, label: "見せるより、自分の近くで大切にしたい" },
      { value: 2, label: "写真をそっと送るくらいがいい" },
      { value: 3, label: "紹介文を添えたい" },
      { value: 4, label: "会話のきっかけにしたい" },
      { value: 5, label: "そこから里親さん同士で話したい" },
    ],
    evidenceByAnswer: evidence("goen-talk", "word-tuner", "uchinoko-world", "warm-watch", "chikuchiku-care"),
  },
  {
    id: "q15",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "紹介文を考える",
    text: "うちの子をひとことで紹介するとしたら、先に考えるのは？",
    primaryType: "word-tuner",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "言葉より、写真で伝えたい" },
      { value: 2, label: "感じたままに話したい" },
      { value: 3, label: "誰に伝えるかで変えたい" },
      { value: 4, label: "伝わりやすい言葉に整えたい" },
      { value: 5, label: "背景や想いまで届く言葉にしたい" },
    ],
    evidenceByAnswer: evidence("word-tuner", "town-finder", "goen-talk", "uchinoko-world", "warm-watch"),
  },
  {
    id: "q16",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "行ってみたい場所",
    text: "うちの子とおでかけするなら、最初に気になるのは？",
    primaryType: "outing-arranger",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "無理なく行ける安心感" },
      { value: 2, label: "誰と一緒なら楽しめそうか" },
      { value: 3, label: "その場所の情報" },
      { value: 4, label: "時間や持ち物の段取り" },
      { value: 5, label: "みんなが動きやすい流れ" },
    ],
    evidenceByAnswer: evidence("outing-arranger", "town-finder", "goen-talk", "warm-watch", "back-pat"),
  },
  {
    id: "q17",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "面白いおの活",
    text: "変わったおの活を思いついたら、近い動きは？",
    primaryType: "mendokushe-breakthrough",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "まずは誰かの反応を見たい" },
      { value: 2, label: "できるか調べてから考える" },
      { value: 3, label: "一緒にやる人がいれば動ける" },
      { value: 4, label: "小さく試してみたい" },
      { value: 5, label: "面白そうならすぐ形にしたい" },
    ],
    evidenceByAnswer: evidence("mendokushe-breakthrough", "tadaima-starter", "goen-talk", "town-finder", "warm-watch"),
  },
  {
    id: "q18",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "未来の楽しみ",
    text: "うちの子との楽しみ方を考えるとき、近いのは？",
    primaryType: "wakuwaku-future",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "今のままでも十分あたたかい" },
      { value: 2, label: "少しずつ増えればいい" },
      { value: 3, label: "誰かと話すと浮かびやすい" },
      { value: 4, label: "いくつか案を出したくなる" },
      { value: 5, label: "まだない楽しみ方を広げたい" },
    ],
    evidenceByAnswer: evidence("wakuwaku-future", "mendokushe-breakthrough", "goen-talk", "chikuchiku-care", "warm-watch"),
  },
  {
    id: "q19",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "里帰りの話",
    text: "里帰りの話題が出たとき、あなたに近いのは？",
    primaryType: "tadaima-starter",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "行ける人の話を聞くだけでもうれしい" },
      { value: 2, label: "情報を見て想像したい" },
      { value: 3, label: "誰かと相談できると動きやすい" },
      { value: 4, label: "行くきっかけを作りたい" },
      { value: 5, label: "誰かを誘って里帰りしたくなる" },
    ],
    evidenceByAnswer: evidence("tadaima-starter", "back-pat", "goen-talk", "town-finder", "warm-watch"),
  },
  {
    id: "q20",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "小さな発見",
    text: "おのくんに関する小さな発見をしたら、近いのは？",
    primaryType: "town-finder",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "自分の中で大切にしたい" },
      { value: 2, label: "近い人にだけ話したい" },
      { value: 3, label: "言葉にして残したい" },
      { value: 4, label: "あとで見返せるようにしたい" },
      { value: 5, label: "誰かの役に立つ形で届けたい" },
    ],
    evidenceByAnswer: evidence("town-finder", "word-tuner", "goen-talk", "warm-watch", "outing-arranger"),
  },
  {
    id: "q21",
    chapter: "enjoy",
    chapterTitle: "第2章 うちの子との楽しみ方",
    scene: "迷っている人",
    text: "おのくんを気にしている人が迷っていたら、どうしたい？",
    primaryType: "back-pat",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "そっと見守りたい" },
      { value: 2, label: "話しやすい空気を作りたい" },
      { value: 3, label: "必要な情報を渡したい" },
      { value: 4, label: "一歩をやさしく後押ししたい" },
      { value: 5, label: "一緒に動けるきっかけを作りたい" },
    ],
    evidenceByAnswer: evidence("back-pat", "tadaima-starter", "town-finder", "goen-talk", "warm-watch"),
  },
  {
    id: "q22",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "LINEで話すなら",
    text: "LINEオープンチャットで話すなら、最初に近い話題は？",
    primaryType: "goen-talk",
    primaryCluster: "grow",
    choices: [
      { value: 1, label: "まずは見るだけで雰囲気を知りたい" },
      { value: 2, label: "うちの子の写真をそっと見せたい" },
      { value: 3, label: "気になる情報を聞いてみたい" },
      { value: 4, label: "うちの子エピソードを話したい" },
      { value: 5, label: "里親さん同士で会話を広げたい" },
    ],
    evidenceByAnswer: evidence("goen-talk", "uchinoko-world", "town-finder", "warm-watch", "word-tuner"),
  },
  {
    id: "q23",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "Discordで関わるなら",
    text: "Discordで企画や準備に関わるなら、近い役割は？",
    primaryType: "word-tuner",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "安心して見られる場所を大切にしたい" },
      { value: 2, label: "場の会話をあたためたい" },
      { value: 3, label: "必要な情報を集めたい" },
      { value: 4, label: "伝わる言葉や案内を整えたい" },
      { value: 5, label: "活動の想いを言葉にして届けたい" },
    ],
    evidenceByAnswer: evidence("word-tuner", "town-finder", "goen-talk", "warm-watch", "outing-arranger"),
  },
  {
    id: "q24",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "防災×帽祭",
    text: "防災×帽祭のような場に関わるなら、近いのは？",
    primaryType: "tadaima-starter",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "安心して集まれる空気を見守りたい" },
      { value: 2, label: "来た人が話しやすいようにしたい" },
      { value: 3, label: "内容をわかりやすく伝えたい" },
      { value: 4, label: "人が来るきっかけを作りたい" },
      { value: 5, label: "楽しく集まる火をつけたい" },
    ],
    evidenceByAnswer: evidence("tadaima-starter", "back-pat", "word-tuner", "goen-talk", "warm-watch"),
  },
  {
    id: "q25",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "場づくり",
    text: "里親さんが集まる小さな場を作るなら、最初に考えるのは？",
    primaryType: "outing-arranger",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "安心できる空気" },
      { value: 2, label: "話しやすいきっかけ" },
      { value: 3, label: "どんな場か伝わる説明" },
      { value: 4, label: "時間や流れの組み立て" },
      { value: 5, label: "みんなが動きやすい段取り" },
    ],
    evidenceByAnswer: evidence("outing-arranger", "back-pat", "word-tuner", "goen-talk", "warm-watch"),
  },
  {
    id: "q26",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "うちの子自慢",
    text: "うちの子自慢をするなら、どんな形が近い？",
    primaryType: "uchinoko-world",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "言葉少なめに、そばに置いておく" },
      { value: 2, label: "好きなところを短く話す" },
      { value: 3, label: "迎えた背景も添える" },
      { value: 4, label: "写真や飾り方で見せたい" },
      { value: 5, label: "うちの子の世界観ごと見せたい" },
    ],
    evidenceByAnswer: evidence("uchinoko-world", "word-tuner", "town-finder", "warm-watch", "goen-talk"),
  },
  {
    id: "q27",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "制作や手しごと",
    text: "おのくんにまつわる手しごとに触れるなら、近いのは？",
    primaryType: "chikuchiku-care",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "完成した姿を写真で見たい" },
      { value: 2, label: "どんな背景か知りたい" },
      { value: 3, label: "誰かと感想を話したい" },
      { value: 4, label: "手ざわりや丁寧さを感じたい" },
      { value: 5, label: "ものと想いを大切に育てたい" },
    ],
    evidenceByAnswer: evidence("chikuchiku-care", "warm-watch", "goen-talk", "town-finder", "uchinoko-world"),
  },
  {
    id: "q28",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "新しい企画",
    text: "おのくんの新しい企画を考えるなら、あなたが出しやすいのは？",
    primaryType: "wakuwaku-future",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "安心して続く形" },
      { value: 2, label: "実際に動く段取り" },
      { value: 3, label: "伝わるコンセプト" },
      { value: 4, label: "楽しみ方が広がる案" },
      { value: 5, label: "未来が見えるわくわくする案" },
    ],
    evidenceByAnswer: evidence("wakuwaku-future", "mendokushe-breakthrough", "word-tuner", "outing-arranger", "warm-watch"),
  },
  {
    id: "q29",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "予想外の遊び",
    text: "おのくんでちょっと笑える企画をするなら、近いのは？",
    primaryType: "mendokushe-breakthrough",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "場があたたかいことを大事にしたい" },
      { value: 2, label: "参加しやすい流れを作りたい" },
      { value: 3, label: "誰かと一緒ならやってみたい" },
      { value: 4, label: "少し変わった案を試したい" },
      { value: 5, label: "めんどくしぇけど面白いことをしたい" },
    ],
    evidenceByAnswer: evidence("mendokushe-breakthrough", "wakuwaku-future", "goen-talk", "outing-arranger", "warm-watch"),
  },
  {
    id: "q30",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "誰かの一歩",
    text: "初参加の里親さんが不安そうなら、近い関わり方は？",
    primaryType: "back-pat",
    primaryCluster: "move",
    choices: [
      { value: 1, label: "無理に話しかけず見守る" },
      { value: 2, label: "近くにいて安心感を作る" },
      { value: 3, label: "何が不安か聞いてみる" },
      { value: 4, label: "参加しやすい一歩を渡す" },
      { value: 5, label: "やさしく背中をぽんと押す" },
    ],
    evidenceByAnswer: evidence("back-pat", "goen-talk", "town-finder", "warm-watch", "outing-arranger"),
  },
  {
    id: "q31",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "地域とのつながり",
    text: "東松島やおのくんの情報を誰かに届けるなら、近い形は？",
    primaryType: "town-finder",
    primaryCluster: "tell",
    choices: [
      { value: 1, label: "必要な人にだけそっと渡す" },
      { value: 2, label: "会話の中で自然に話す" },
      { value: 3, label: "わかりやすい言葉にする" },
      { value: 4, label: "行きたい人向けにまとめる" },
      { value: 5, label: "発見した魅力を広げたい" },
    ],
    evidenceByAnswer: evidence("town-finder", "word-tuner", "goen-talk", "warm-watch", "tadaima-starter"),
  },
  {
    id: "q32",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "安心の場",
    text: "里親さんの集まりで、あなたが大切にしたい空気は？",
    primaryType: "warm-watch",
    primaryCluster: "grow",
    choices: [
      { value: 1, label: "新しい話題がどんどん出る空気" },
      { value: 2, label: "情報が見つかりやすい空気" },
      { value: 3, label: "話したい人が話せる空気" },
      { value: 4, label: "初めてでもほっとできる空気" },
      { value: 5, label: "帰ってこられる家族みたいな空気" },
    ],
    evidenceByAnswer: evidence("warm-watch", "goen-talk", "town-finder", "wakuwaku-future", "mendokushe-breakthrough"),
  },
  {
    id: "q33",
    chapter: "quest",
    chapterTitle: "第3章 ご縁を広げるクエスト",
    scene: "次のご縁",
    text: "診断が終わったあと、今の気分に近い次の一歩は？",
    primaryType: "tadaima-starter",
    primaryCluster: "create",
    choices: [
      { value: 1, label: "うちの子とゆっくり過ごしたい" },
      { value: 2, label: "うちの子の写真を見返したい" },
      { value: 3, label: "結果を読んで言葉にしたい" },
      { value: 4, label: "誰かと結果を話してみたい" },
      { value: 5, label: "ご縁が広がる場所をのぞいてみたい" },
    ],
    evidenceByAnswer: evidence("tadaima-starter", "goen-talk", "word-tuner", "uchinoko-world", "warm-watch"),
  },
];

export const ONOKUN_SATOOYA_TOTAL_QUESTIONS = onokunSatooyaQuestions.length;
